"""::: Code Generated by Copilot 7c8c37bf-e44b-45a7-b5cd-d25d32b40f9d. This comment will be removed automatically after the file is saved :::
上下文工程 (Context Engineering) — 演示入口

核心理念 (Andrej Karpathy, 2025):
  "Prompt Engineering 时代结束了，Context Engineering 时代开始了。"
  不再是 "怎么写好 prompt"，而是 "怎么把正确的信息在正确的时间喂给 LLM"。

运行: python 35_context_engineering/main.py
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

try:
    from context_assembler import ContextAssembler, ContextBudget, ContextBlock
    from window_manager import (Message, SlidingWindowManager, SummaryCompressor,
                                ImportanceFilter, AdaptiveWindowManager)
    from dynamic_context import (DynamicFewShotSelector, Example, ToolPruner, ToolDef,
                                 PersonalizedContext, UserProfile, PromptCache)
except ImportError:
    from .context_assembler import ContextAssembler, ContextBudget, ContextBlock
    from .window_manager import (Message, SlidingWindowManager, SummaryCompressor,
                                 ImportanceFilter, AdaptiveWindowManager)
    from .dynamic_context import (DynamicFewShotSelector, Example, ToolPruner, ToolDef,
                                  PersonalizedContext, UserProfile, PromptCache)


def demo_context_assembly():
    print("▶ 1. 上下文组装 — 多来源信息优先级排列")
    print("─" * 60)

    budget = ContextBudget("gpt-4o-mini", reserve_output=4096)
    assembler = ContextAssembler(budget)

    # 添加各层上下文
    assembler.add_instruction("你是 SmartFlow 技术支持助手。只回答产品相关问题。")
    assembler.add_knowledge("产品文档", "SmartFlow 支持工作流自动化，包括审批流、数据流、集成流。定价: 基础版¥99/月，企业版¥999/月。")
    assembler.add_knowledge("常见问题", "Q: 如何重置密码？A: 进入设置→安全→重置密码。Q: 如何导出数据？A: 进入报表→导出。")
    assembler.add_memory("用户历史", "用户上次询问了部署相关问题，偏好简洁回答。")
    assembler.add_tool_def("search_kb", '{"name": "search_kb", "description": "搜索知识库"}')
    assembler.add_tool_def("create_ticket", '{"name": "create_ticket", "description": "创建工单"}')
    assembler.add_example("示例1", "Q: 价格多少？\nA: 基础版¥99/月，企业版¥999/月。")
    assembler.add_user_message("SmartFlow 企业版有哪些功能？")

    result = assembler.assemble()

    print(f"  上下文来源: {result['stats']['total_blocks']} 块")
    print(f"  选中: {result['stats']['selected_blocks']} 块, 丢弃: {result['stats']['dropped_blocks']} 块")
    print(f"  Token 估算: {result['stats']['estimated_tokens']}, 预算使用: {result['stats']['budget_usage']}")
    print(f"\n  组装后 messages ({len(result['messages'])} 条):")
    for msg in result["messages"]:
        role = msg["role"]
        content = msg["content"][:80].replace("\n", " ")
        print(f"    [{role}] {content}...")


def demo_window_management():
    print(f"\n\n▶ 2. 对话窗口管理 — 三种策略对比")
    print("─" * 60)

    # 模拟一个长对话
    messages = [
        Message("system", "你是技术助手。"),
        Message("user", "什么是 RAG？", turn=1),
        Message("assistant", "RAG 是检索增强生成，通过检索外部知识来增强 LLM 的回答能力。核心步骤是加载→分片→嵌入→检索→生成。", turn=1),
        Message("user", "好的，谢谢", turn=2),
        Message("assistant", "不客气！还有什么问题吗？", turn=2),
        Message("user", "FAISS 和 Chroma 选哪个？", turn=3),
        Message("assistant", "FAISS 适合大规模单机场景，速度最快；Chroma 适合轻量开发，内置元数据过滤。如果数据量 < 100万，选 Chroma；> 100万选 FAISS。", turn=3),
        Message("user", "总结一下到目前为止讨论的重点", turn=4, importance=0.9),
        Message("assistant", "总结：1. RAG 五步流程 2. FAISS 适合大规模，Chroma 适合轻量 3. 数据量是选型关键", turn=4),
        Message("user", "嗯", turn=5),
        Message("assistant", "好的，继续问吧！", turn=5),
        Message("user", "如何部署到生产环境？需要考虑哪些因素？错误处理怎么做？", turn=6),
        Message("assistant", "生产部署需要考虑：1. 容器化(Docker) 2. 健康检查 3. 优雅关闭 4. 配置管理 5. 日志 6. 监控告警。错误处理用重试+熔断+降级。", turn=6),
    ]

    total_tokens = sum(m.token_estimate for m in messages)
    print(f"  原始: {len(messages)} 条消息, ~{total_tokens} tokens\n")

    # 策略1: 滑动窗口
    slider = SlidingWindowManager(max_turns=3)
    slided = slider.trim(messages)
    print(f"  滑动窗口 (保留3轮): {len(slided)} 条, ~{sum(m.token_estimate for m in slided)} tokens")

    # 策略2: 摘要压缩
    compressor = SummaryCompressor(keep_recent=4)
    compressed = compressor.compress(messages)
    print(f"  摘要压缩 (保留4条): {len(compressed)} 条, ~{sum(m.token_estimate for m in compressed)} tokens")
    for m in compressed:
        if "[对话摘要]" in m.content:
            print(f"    摘要: {m.content[:60]}...")

    # 策略3: 重要性过滤
    imp_filter = ImportanceFilter()
    filtered = imp_filter.filter(messages, token_budget=300)
    print(f"  重要性过滤 (预算300): {len(filtered)} 条, ~{sum(m.token_estimate for m in filtered)} tokens")

    # 策略4: 自适应
    adaptive = AdaptiveWindowManager(token_budget=300, keep_recent=4)
    result = adaptive.manage(messages)
    print(f"  自适应 (预算300): {len(result['messages'])} 条, ~{result['final_tokens']} tokens, 策略={result['strategy']}")


def demo_dynamic_fewshot():
    print(f"\n\n▶ 3. 动态 Few-shot 选择")
    print("─" * 60)

    selector = DynamicFewShotSelector()

    examples = [
        Example("如何重置密码", "进入设置→安全→重置密码", "账户"),
        Example("忘记用户名", "用注册邮箱找回用户名", "账户"),
        Example("如何创建工作流", "进入流程设计器→新建→拖拽节点", "功能"),
        Example("API 调用限流了", "检查 API Key 配额，升级套餐", "技术"),
        Example("数据库连接失败", "检查连接字符串、防火墙、端口", "技术"),
        Example("如何导出报表", "进入报表中心→选择类型→导出PDF/Excel", "功能"),
        Example("退款流程", "联系客服提交退款申请，3个工作日处理", "账户"),
    ]
    for ex in examples:
        selector.add(ex)

    queries = ["我的密码忘了怎么办", "数据库报错了", "怎么生成月度报告"]
    for q in queries:
        selected = selector.select(q, top_k=2)
        print(f"  Q: {q}")
        for ex in selected:
            print(f"    → 示例: {ex.query} → {ex.response[:30]}  [{ex.category}]")
        print()


def demo_tool_pruning():
    print(f"\n\n▶ 4. 工具定义裁剪")
    print("─" * 60)

    tools = [
        ToolDef("search_knowledge", "搜索知识库", "knowledge", 80),
        ToolDef("create_ticket", "创建工单", "ticket", 60),
        ToolDef("update_ticket", "更新工单状态", "ticket", 60),
        ToolDef("delete_ticket", "删除工单", "ticket", 50),
        ToolDef("get_weather", "获取天气", "utility", 40),
        ToolDef("send_email", "发送邮件", "communication", 70),
        ToolDef("query_database", "查询数据库", "data", 90),
        ToolDef("export_report", "导出报表", "data", 60),
        ToolDef("translate_text", "翻译文本", "utility", 50),
        ToolDef("schedule_meeting", "安排会议", "calendar", 60),
        ToolDef("manage_user", "用户管理", "admin", 70),
        ToolDef("system_status", "系统状态", "admin", 40),
    ]
    pruner = ToolPruner(tools)

    print(f"  全部工具: {len(tools)} 个, ~{pruner.total_tokens} tokens\n")

    queries = ["我要创建一个工单", "帮我查数据库导出报表", "今天天气怎么样"]
    for q in queries:
        pruned = pruner.prune(q, max_tools=3)
        print(f"  Q: {q}")
        print(f"    → 保留: {[t.name for t in pruned]} (~{sum(t.schema_tokens for t in pruned)} tokens)")


def demo_personalization():
    print(f"\n\n▶ 5. 用户画像个性化")
    print("─" * 60)

    ctx = PersonalizedContext()

    profiles = [
        UserProfile("u1", "developer", "zh-CN", "expert", {"concise": True}),
        UserProfile("u2", "customer", "zh-CN", "beginner"),
        UserProfile("u3", "admin", "en-US", "intermediate"),
    ]

    for p in profiles:
        instruction = ctx.build_context(p)
        print(f"  {p.role}/{p.expertise}/{p.language}:")
        for line in instruction.split("\n"):
            print(f"    {line}")
        print()


def demo_prompt_cache():
    print(f"\n\n▶ 6. Prompt 缓存（Anthropic 风格）")
    print("─" * 60)

    cache = PromptCache()

    # 构建缓存消息
    messages = cache.build_cached_messages(
        system_prompt="你是 SmartFlow 技术助手..." + " " * 2000,  # 长 system prompt
        tool_definitions='[{"name": "search"}, {"name": "ticket"}]' + " " * 1000,
        user_message="请帮我查一下工单 TK-001",
    )

    print(f"  消息结构:")
    for msg in messages:
        role = msg["role"]
        if isinstance(msg.get("content"), list):
            for part in msg["content"]:
                cached = "✅ CACHED" if "cache_control" in part else "❌ NO CACHE"
                print(f"    [{role}] {part['text'][:40]}... → {cached}")
        else:
            print(f"    [{role}] {msg['content'][:40]}... → ❌ NO CACHE (每次不同)")

    # 费用估算
    savings = cache.estimate_savings(cached_tokens=3000, calls=100)
    print(f"\n  费用估算 (3000 tokens 缓存, 100 次调用):")
    print(f"    无缓存: {savings['no_cache_cost']}")
    print(f"    有缓存: {savings['cached_cost']}")
    print(f"    节省:   {savings['savings']} ({savings['savings_pct']})")


def main():
    print("=== 上下文工程 (Context Engineering) ===\n")
    demo_context_assembly()
    demo_window_management()
    demo_dynamic_fewshot()
    demo_tool_pruning()
    demo_personalization()
    demo_prompt_cache()

    print(f"\n\n{'=' * 60}")
    print("📊 上下文工程总结:")
    print(f"""
  Prompt Engineering          Context Engineering
  ─────────────────          ──────────────────────
  写好一个 prompt              动态组装最优上下文
  静态模板                     多来源 + 优先级 + 预算
  一次性                       每次请求都重新组装
  关注"怎么问"                 关注"喂什么信息"

  上下文六层架构:
  ┌──────────────────────────────────────┐
  │ 指令层  │ System Prompt（静态）       │
  │ 知识层  │ RAG 检索 / 知识图谱（动态） │
  │ 记忆层  │ 对话历史 / 长期记忆（动态） │
  │ 工具层  │ 工具定义 + 执行结果（动态） │
  │ 示例层  │ 动态 Few-shot（动态）       │
  │ 用户层  │ 当前消息（实时）            │
  └──────────────────────────────────────┘

  优化技术:
  - 上下文预算管理  → 按优先级分配 token
  - 窗口管理       → 滑动窗口/摘要/重要性过滤
  - 动态 Few-shot  → 按相似度选示例
  - 工具裁剪       → 只暴露相关工具
  - 用户画像       → 个性化 system prompt
  - Prompt 缓存    → 不变前缀缓存（省 90% 输入费用）""")


if __name__ == "__main__":
    main()
