"""::: Code Generated by Copilot a7d42ec1-57de-43f9-a8b0-278123864720. This comment will be removed automatically after the file is saved :::
结构化输出 — 演示入口

运行: python -m 29_structured_output.main
或:   python 29_structured_output/main.py
"""

import json
import os
import sys
from dataclasses import dataclass, field
from enum import Enum

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# ::: Code Generated by Copilot a7d42ec1-57de-43f9-a8b0-278123864720. This comment will be removed automatically after the file is saved :::
# 兼容 python 29_structured_output/main.py 和 python -m 运行
try:
    from schema_engine import SchemaGenerator, SchemaValidator, JSONRepair
    from function_calling import ToolRegistry, FunctionCallingSimulator
    from output_parser import OutputParser, DataclassParser, RetryParser, MultiFormatExtractor
except ImportError:
    from .schema_engine import SchemaGenerator, SchemaValidator, JSONRepair
    from .function_calling import ToolRegistry, FunctionCallingSimulator
    from .output_parser import OutputParser, DataclassParser, RetryParser, MultiFormatExtractor


# ── 演示用数据结构 ─────────────────────────────────────────

class Priority(Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


@dataclass
class TicketAnalysis:
    """工单分析结果。"""
    category: str
    priority: str
    summary: str
    suggested_actions: list[str] = field(default_factory=list)
    confidence: float = 0.9


# ═══════════════════════════════════════════════════════════
# Demo 1: JSON Schema 生成 + 验证
# ═══════════════════════════════════════════════════════════

def demo_schema():
    print("▶ 1. JSON Schema 生成 + 验证")
    print("─" * 60)

    # 从 dataclass 生成
    schema = SchemaGenerator.from_dataclass(TicketAnalysis)
    print("  从 dataclass 生成 Schema:")
    print(f"    {json.dumps(schema, indent=4, ensure_ascii=False)[:300]}...")

    # 验证正确数据
    validator = SchemaValidator(schema)
    good_data = {
        "category": "技术支持",
        "priority": "high",
        "summary": "用户无法登录系统",
        "suggested_actions": ["检查密码", "重置账号"],
        "confidence": 0.85,
    }
    errors = validator.validate(good_data)
    print(f"\n  验证正确数据: {'✅ 通过' if not errors else f'❌ {errors}'}")

    # 验证错误数据
    bad_data = {
        "category": "技术支持",
        # 缺少 priority, summary
        "confidence": "很高",  # 类型错误
        "extra_field": True,   # 额外字段
    }
    errors = validator.validate(bad_data)
    print(f"  验证错误数据: ❌")
    for e in errors:
        print(f"    - {e}")

    # 从简单 dict 生成
    simple_schema = SchemaGenerator.from_dict({"name": "string", "age": "integer", "active": "boolean"})
    print(f"\n  从 dict 生成: {json.dumps(simple_schema, ensure_ascii=False)}")


# ═══════════════════════════════════════════════════════════
# Demo 2: JSON 修复
# ═══════════════════════════════════════════════════════════

def demo_json_repair():
    print(f"\n\n▶ 2. JSON 修复 — 处理 LLM 常见格式错误")
    print("─" * 60)

    broken_outputs = [
        ("尾部逗号", '{"name": "张三", "age": 25,}'),
        ("单引号", "{'name': '李四', 'age': 30}"),
        ("代码块包裹", '```json\n{"result": "ok"}\n```'),
        ("无引号 key", '{name: "王五", age: 28}'),
        ("Python 布尔", '{"active": True, "deleted": False, "data": None}'),
        ("混合错误", "```\n{name: '赵六', active: True, tags: ['vip',],}\n```"),
    ]

    for desc, raw in broken_outputs:
        data, status = JSONRepair.safe_parse(raw)
        icon = "✅" if data else "❌"
        print(f"  {icon} {desc:12s} → {json.dumps(data, ensure_ascii=False) if data else status}")


# ═══════════════════════════════════════════════════════════
# Demo 3: Function Calling 流程
# ═══════════════════════════════════════════════════════════

def demo_function_calling():
    print(f"\n\n▶ 3. Function Calling 完整流程")
    print("─" * 60)

    # 注册工具
    registry = ToolRegistry()

    def get_weather(city: str, unit: str = "celsius") -> dict:
        """获取指定城市的天气信息。"""
        data = {"上海": 32, "北京": 28, "深圳": 35}
        return {"city": city, "temp": data.get(city, 20), "unit": unit, "condition": "晴"}

    def search_order(order_id: str) -> dict:
        """查询订单详情。"""
        return {"order_id": order_id, "status": "已发货", "amount": 299.0}

    registry.register(get_weather, "获取城市天气",
                      {"city": "城市名称", "unit": "温度单位 (celsius/fahrenheit)"})
    registry.register(search_order, "查询订单信息",
                      {"order_id": "订单编号"})

    # 展示生成的 OpenAI tools 格式
    tools = registry.to_openai_tools()
    print("  注册的工具 (OpenAI 格式):")
    for t in tools:
        print(f"    {t['function']['name']}: {t['function']['description']}")
        print(f"      params: {list(t['function']['parameters']['properties'].keys())}")

    # 模拟完整流程
    sim = FunctionCallingSimulator(registry)
    tests = [
        ("查一下上海的 get_weather", {"city": "上海"}),
        ("帮我 search_order ORD-001", {"order_id": "ORD-001"}),
        ("你好，今天天气怎么样", None),  # 不触发工具
    ]

    for user_msg, args in tests:
        result = sim.run(user_msg, tool_args=args)
        print(f"\n  用户: {user_msg}")
        if result["tool_called"]:
            print(f"    → 工具: {result['tool_called']}({result['tool_args']})")
            print(f"    → 结果: {result['tool_result']}")
        else:
            print(f"    → 未调用工具 (直接回答)")
        print(f"    → Messages: {result['messages_count']} 条")


# ═══════════════════════════════════════════════════════════
# Demo 4: Dataclass 解析 + 重试修复
# ═══════════════════════════════════════════════════════════

def demo_parsing_retry():
    print(f"\n\n▶ 4. Dataclass 解析 + 重试修复")
    print("─" * 60)

    parser = DataclassParser(TicketAnalysis)

    # 正确输出
    good = '{"category": "技术支持", "priority": "high", "summary": "登录失败", "suggested_actions": ["重置密码"], "confidence": 0.9}'
    result, errors = parser.parse(good)
    print(f"  正确输出: {'✅' if result else '❌'} {result}")

    # 格式错误但可修复
    broken = "```json\n{category: '网络问题', priority: 'medium', summary: '网速慢', suggested_actions: ['检查路由器',], confidence: 0.7}\n```"
    result, errors = parser.parse(broken)
    print(f"  修复后解析: {'✅' if result else '❌'} {result}")

    # 重试修复演示
    print(f"\n  重试修复流程:")
    bad_output = '{"category": "bug"}'  # 缺少必填字段

    def mock_fix(errors, raw, prompt):
        # 模拟 LLM 根据错误修复输出
        return '{"category": "bug", "priority": "high", "summary": "系统崩溃", "suggested_actions": ["重启"]}'

    retry = RetryParser(parser, max_retries=2)
    result, attempts = retry.parse_with_retry(bad_output, mock_fix_fn=mock_fix)
    for a in attempts:
        icon = "✅" if a["success"] else "❌"
        print(f"    第 {a['attempt']} 次: {icon} errors={a['errors'][:2] if a['errors'] else '无'}")
    print(f"    最终结果: {result}")


# ═══════════════════════════════════════════════════════════
# Demo 5: 多格式抽取
# ═══════════════════════════════════════════════════════════

def demo_multi_format():
    print(f"\n\n▶ 5. 多格式抽取")
    print("─" * 60)

    mixed_output = """好的，以下是分析结果：

```json
{"category": "退款", "priority": "high"}
```

<reasoning>用户明确要求退款，属于高优先级</reasoning>

- **处理人**: 李经理
- **预计时间**: 2小时
- **状态**: 待处理"""

    print("  原文:")
    for line in mixed_output.strip().split("\n")[:3]:
        print(f"    {line}")
    print(f"    ...")

    jsons = MultiFormatExtractor.extract_json(mixed_output)
    print(f"\n  JSON 抽取: {jsons}")

    xml = MultiFormatExtractor.extract_xml_tags(mixed_output, "reasoning")
    print(f"  XML 标签: {xml}")

    kv = MultiFormatExtractor.extract_key_value(mixed_output)
    print(f"  Key-Value: {kv}")


# ═══════════════════════════════════════════════════════════

def main():
    print("=== 结构化输出 (Structured Output) ===\n")
    demo_schema()
    demo_json_repair()
    demo_function_calling()
    demo_parsing_retry()
    demo_multi_format()

    print(f"\n\n{'=' * 60}")
    print("📊 结构化输出总结:")
    print(f"""
  技术栈          │ 说明
  ───────────────┼──────────────────────────────────
  JSON Schema     │ 约束输出格式的标准（OpenAI 原生支持）
  Function Call   │ LLM 结构化调工具的底层机制
  Pydantic        │ Python 最强类型校验（pydantic-ai 核心）
  JSON Repair     │ 修复 LLM 常见格式错误（尾逗号/单引号/布尔）
  Retry Parser    │ 解析失败 → 构建修复 prompt → LLM 重试
  多格式抽取       │ 从混合输出中提取 JSON/XML/KV

  框架支持:
  - OpenAI: response_format={"type": "json_schema", ...}
  - pydantic-ai: output_type=MyModel（自动 Schema + 验证）
  - LangChain: PydanticOutputParser / JsonOutputParser
  - Vercel AI SDK: generateObject() + Zod schema
  - Spring AI: BeanOutputConverter<T>""")


if __name__ == "__main__":
    main()
